@Api_HostAddress = http://localhost:5010

POST {{Api_HostAddress}}/api/codicefiscale/genera
Accept: application/json

###

POST {{Api_HostAddress}}/api/iban/genera
Content-Type: application/json
Accept: application/json
{

}

###

POST {{Api_HostAddress}}/api/iban/genera
Accept: application/json
{
  "countryCode": "DE"
}
